# http fan tasks
- name: we need nginx
  apt: pkg=nginx state=installed

- name: configure http fan
  template: src=nginx_proxy.conf dest=/etc/nginx/sites-enabled/{{ app_name }}_fan.conf
  notify:
    - restart nginx

- name: run and enable nginx
  service: name=nginx state=running enabled=yes
